### ISSUE TITLE
 Start pointer should be before end pointer 

### ISSUE THREAD

**Issue by CATboardBETA** [elegoff/sonar-rust#51] opened 2022-06-06 16:20 UTC
Right after successfully analyzing my file `lib.rs`, sonar-scanner gives me this error: 
```sh
java.lang.IllegalArgumentException: Start pointer [line=1, lineOffset=0] should be before end pointer [line=1, lineOffset=0]
```
I'm using this script to launch it: 
```bash
#!/bin/bash
grcov ./target/debug/ -s . -t cobertura --llvm --branch --ignore-not-existing -o ./target/debug/coverage.xml
cargo +nightly clippy --message-format=json >| TEMP_CLIPPY.json

sudo sonar-scanner -X \
  -Dsonar.projectKey=qiish-parse \
  -Dsonar.sources=./src/ \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=<MY_TOKEN> \
```
(<MY_TOKEN> is replaced with my token in the script).
Here's `lib.rs`: [gist](https://gist.github.com/CATboardBETA/b6a7968f8ef3cf7e0b4b91348d4c05ec)

And here's my sonar-project.properties file: 
```properties
community.rust.clippy.reportPaths = TEMP_CLIPPY.json
community.rust.cobertura.reportPaths = target/debug/coverage.xml
```

This is a repost of my sonarsource forum post: https://community.sonarsource.com/t/start-pointer-should-be-before-end-pointer/

**Comment by CATboardBETA** [comment] 2022-06-07 17:14
I happened to notice that the output in TEMP_CLIPPY.json has many outer elements, not in an array or even seperrated with commas. How strange.
Might be an issue with clippy.

**Comment by elegoff** [comment] 2022-06-08 16:30
The PR https://github.com/elegoff/sonar-rust/pull/52 fixing the issue is merged on the master branch

The problem was for clippy issues not defining a text range on the source code, typically issues like [clippy::cargo_common_metadata ](https://rust-lang.github.io/rust-clippy/master/index.html#cargo_common_metadata)

**Closed by elegoff** 2022-06-08 16:30 UTC
